# Generated by Django 4.1.3 on 2022-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='id_name',
            field=models.CharField(default='blank', max_length=32, verbose_name='идентификатор'),
            preserve_default=False,
        ),
    ]
