# Generated by Django 4.1.3 on 2022-11-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertype_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='идентификатор'),
        ),
    ]
