# Generated by Django 4.1.3 on 2022-11-16 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='название группы')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='дата начала учебы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='дата завершения учебы')),
                ('is_end', models.BooleanField(default=False, verbose_name='обучение закончено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'ordering': ('-date_end',),
            },
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='закончил обучение')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classrooms.classroom', verbose_name='группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'группа студента',
                'verbose_name_plural': 'группы студентов',
                'ordering': ['classroom'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lesson', models.DateTimeField(verbose_name='дата проведения занятия')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='classrooms.classroom', verbose_name='группа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='урок')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'расписание занятий',
                'ordering': ['-date_of_lesson'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, verbose_name='ссылка на домашнее задание')),
                ('need_to_fix', models.BooleanField(default=False, verbose_name='требует доработки')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='работа выполнена верно')),
                ('date_of_publication', models.DateTimeField(auto_now_add=True, verbose_name='дата сдачи работы')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classrooms.schedule', verbose_name='урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'домашнее задание',
                'verbose_name_plural': 'домашние задания',
            },
        ),
        migrations.AddConstraint(
            model_name='studentclassroom',
            constraint=models.UniqueConstraint(fields=('classroom', 'student'), name='unique_student_classroom'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('student', 'schedule'), name='unique_student_schedule'),
        ),
    ]
