# Generated by Django 4.1.3 on 2022-11-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=32, verbose_name='название запроса')),
                ('text', models.TextField(verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'ответ бота',
                'verbose_name_plural': 'ответы бота',
            },
        ),
    ]
