# Generated by Django 4.1.3 on 2022-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botanswer',
            name='query',
            field=models.CharField(max_length=32, unique=True, verbose_name='название запроса'),
        ),
    ]
